### ISSUE TITLE
packagist.org is not updated

### ISSUE THREAD

**Issue by eduardoalonsoalbella** [eastslopestudio/craft3-sites-field#11]
Currently packagist.org has 1.0.0 as the latest version, instead of 1.0.1

https://packagist.org/packages/eastslopestudio/craft3-sites-field#1.0.0

Could you update packagist manually?
(Last update: 2021-12-05 06:01:59 UTC )

Thanks

**Comment by eduardoalonsoalbella** [comment]
@ryanscherler could you update packagist? Thanks!

**Comment by ryanscherler** [comment]
@eduardoalonsoalbella Ok should be good to go 1.0.2 release!
