### ISSUE TITLE
Adding admin column causes error 

### ISSUE THREAD

**Issue by dr-codswallop** [eastslopestudio/craft3-sites-field#13]
When adding this field as a display column on an entries index page it causes a red "a server error occurred" flash notice in the control panel and the column does not get added.

Not sure I've narrowed down the exact error in the logs but I think it might be related to this:
`[error][yii\base\ErrorException:8] yii\base\ErrorException: Array to string conversion in /Users/xxx/Sites/demosite.local/vendor/craftcms/cms/src/base/Field.php:539`

**Comment by ryanscherler** [comment]
@eduardoalonsoalbella could this be related to moving to UID's?

**Comment by eduardoalonsoalbella** [comment]
@ryanscherler the data structure is still the same, the only change is the data type from int to string, @dr-codswallop you might need to "configure the whitelistes sites" that use this plugin and try again

**Comment by ryanscherler** [comment]
@dr-codswallop looks like "configuring the whitelistes sites" that use this plugin seems to resolve the issue after some initial testing. I'm going to close out this issue - feel free to re-open a new one if we've missed something. Thanks!
