### ISSUE TITLE
Bug: Cannot unselect all when using muliple

### ISSUE THREAD

**Issue by vandres** [eastslopestudio/craft3-sites-field#14]
That line 

https://github.com/eastslopestudio/craft3-sites-field/blob/db30be606a442c72e068be411ced1cecd5616993/src/templates/_input.html#L5

should be

```twig
<input type="hidden" name="{{ field.handle }}" value="">
```

**Comment by ryanscherler** [comment]
@vandres Do you mind putting in a PR and I can merge in?
