### ISSUE TITLE
Craft Store still says this plugin is not compatible with craft 4

### ISSUE THREAD

**Issue by eduardoalonsoalbella** [eastslopestudio/craft3-sites-field#17]
Hi, maybe you need to enable something in the craft store

**Comment by ryanscherler** [comment]
I'm not sure why it's not allowing for Craft 4. The console doesn't seem to have an option for selecting a version. Wondering if we think about creating a new plugin for this? @eduardoalonsoalbella would you be interested in taking on maintaining / owning this plugin?

**Comment by ryanscherler** [comment]
Went ahead and updated the plugin to work for both Craft 3 and 4. Tagged a release v1.0.5
