### ISSUE TITLE
Craft 5?

### ISSUE THREAD

**Issue by janhenckens** [eastslopestudio/craft3-sites-field#18]
Any plans for a Craft 5 version?
I'd be happy to have a try at a pull request for this, if you'd accept that?

**Comment by yannkost** [comment]
I have seen that there is no special update required, simply editing the composer.json and updating the require condition by adding Craft 5 are enough. A simple update to the repository should indeed be enough.

**Comment by likeabas** [comment]
@ryanscherler I've created a pull request to add craft 5 support. Would you mind checking and merging?
https://github.com/eastslopestudio/craft-sites-field/pull/19

**Comment by ryanscherler** [comment]
Yep - seems to work fine for me - will merge now. Thanks @likeabas !

**Comment by likeabas** [comment]
Thank you! @ryanscherler should the tags be updated perhaps?

**Comment by tibbis** [comment]
how do I install it? its not available in the plugin store yet.

**Comment by likeabas** [comment]
@ryanscherler @tibbis updating the tags will probably solve that

**Comment by ryanscherler** [comment]
Just tagged a new release - should show up in the plugin store for Craft 5 shortly.

**Comment by likeabas** [comment]
Thanks!!
